sass:
    sass_dir: css

highlighter: rouge
exclude:
    - /serve.bat
    - /setup.txt
    - /Gemfile
    - /Gemfile.lock
    - /node_modules/
    - /package.json
    - /package-lock.json
    - /widgets/

plugins:
    - jekyll-feed

theme: